version: "3"

services:
  technical-test-quartz:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: technical-test-quartz
    restart: always
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 3000:3000
